spring.application.name=backend


#DB config
spring.datasource.url=jdbc:mysql://db/spotify_clone
spring.datasource.username=root
spring.datasource.password=3737
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#security config
spring.security.user.name=myuser
spring.security.user.password=mypassword
